
alib grlib grlib.lib 
alib ec ec.lib 
alib unisim unisim.lib 
alib secureip secureip.lib 
alib unimacro unimacro.lib 
alib altera altera.lib 
alib altera_mf altera_mf.lib 
alib stratixii stratixii.lib 
alib eclipsee eclipsee.lib 
alib cycloneiii cycloneiii.lib 
alib stratixiii stratixiii.lib 
alib simprim simprim.lib 
alib virage virage.lib 
alib atc18 atc18.lib 
alib umc18 umc18.lib 
alib saed32 saed32.lib 
alib synplify synplify.lib 
alib techmap techmap.lib 
alib spw spw.lib 
alib eth eth.lib 
alib opencores opencores.lib 
alib gaisler gaisler.lib 
alib esa esa.lib 
alib fmf fmf.lib 
alib spansion spansion.lib 
alib gsi gsi.lib 
alib cypress cypress.lib 
alib micron micron.lib 
alib work work.lib 
