# Formality script to read reference design
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/stdlib/version.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/stdlib/config_types.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/stdlib/config.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/stdlib/stdlib.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/sparc/sparc.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/modgen/multlib.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/modgen/leaves.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/amba.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/devices.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/defmst.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/apbctrl.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/apbctrlx.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/apbctrldp.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/apbctrlsp.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/ahbctrl.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/dma2ahb_pkg.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/dma2ahb.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/amba/ahbmst.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/dftlib/dftlib.vhd
read_vhdl -r -libname grlib /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/grlib/dftlib/synciotest.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/gencomp/gencomp.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/gencomp/netcomp.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/memory_inferred.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/ddr_inferred.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/mul_inferred.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/ddr_phy_inferred.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/ddrphy_datapath.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/inferred/fifo_inferred.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/virage/memory_virage.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/atc18/pads_atc18.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/umc18/memory_umc18.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/umc18/pads_umc18.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/saed32/clkgen_saed32.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/saed32/pads_saed32.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/saed32/memory_saed32.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/allclkgen.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/techbuf.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/allddr.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/allmem.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/allmul.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/allpads.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/alltap.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkgen.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkmux.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkinv.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkand.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/grgates.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/ddr_ireg.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/ddr_oreg.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/clkpad_ds.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/inpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/inpad_ds.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/iodpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/iopad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/iopad_ds.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/lvds_combo.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/odpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/outpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/outpad_ds.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/toutpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/toutpad_ds.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/skew_outpad.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/ddrphy.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram64.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram_2p.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram_dp.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncfifo_2p.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/regfile_3p.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/tap.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/nandtree.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/grlfpw_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/grfpw_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/leon3_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/leon4_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/mul_61x61.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/cpu_disas_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/ringosc.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/grpci2_phy_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/system_monitor.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/inpad_ddr.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/outpad_ddr.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/iopad_ddr.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram128bw.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram256bw.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram128.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram156bw.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/techmult.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/spictrl_net.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/scanreg.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncrambw.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncram_2pbw.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/sdram_phy.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/syncreg.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/serdes.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/iopad_tm.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/toutpad_tm.vhd
read_vhdl -r -libname techmap /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/techmap/maps/memrwcol.vhd
read_vhdl -r -libname spw /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/spw/comp/spwcomp.vhd
read_vhdl -r -libname spw /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/spw/wrapper/grspw_gen.vhd
read_vhdl -r -libname spw /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/spw/wrapper/grspw2_gen.vhd
read_vhdl -r -libname spw /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/spw/wrapper/grspw_codec_gen.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/comp/ethcomp.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/greth_pkg.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/eth_rstgen.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/eth_edcl_ahb_mst.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/eth_ahb_mst.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/greth_tx.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/greth_rx.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/core/grethc.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/wrapper/greth_gen.vhd
read_vhdl -r -libname eth /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/eth/wrapper/greth_gbit_gen.vhd
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/can/cancomp.vhd
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/can/can_top.vhd
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/i2c/i2coc.vhd
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/clean_rst.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/decoder_8b10b.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/encoder_8b10b.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_constants.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_regs.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_test.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/timescale.v
read_vhdl -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_comp.vhd
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_an.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_mdio.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_rx.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_sync.v
read_verilog -r -libname opencores /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/opencores/ge_1000baseX/ge_1000baseX_tx.v
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/arith/arith.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/arith/mul32.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/arith/div32.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/memctrl/memctrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/memctrl/sdctrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/memctrl/sdctrl64.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/memctrl/sdmctrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/memctrl/srctrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmuconfig.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmuiface.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/libmmu.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmutlbcam.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmulrue.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmulru.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmutlb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmutw.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/srmmu/mmu.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3/leon3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3/grfpushwx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/tbufmem.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/tbufmem_2p.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/dsu3x.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/dsu3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/dsu3_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/libfpu.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/libiu.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/libcache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/libleon3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/regfile_3p_l3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/mmu_acache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/mmu_icache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/mmu_dcache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/cachemem.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/mmu_cache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/grfpwx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/grlfpwx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/iu3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/proc3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/grfpwxsh.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/leon3x.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/leon3cg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/leon3s.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/leon3sh.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/l3stat.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon3v3/cmvalidbits.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/leon4/leon4.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/irqmp/irqmp.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/l2cache/pkg/l2cache.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/can.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/can_mod.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/can_oc.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/can_mc.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/canmux.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/can/can_rd.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/misc.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/rstgen.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/gptimer.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbram.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbdpram.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbtrace_mmb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbtrace_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbtrace.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/grgpio.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahbstat.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/logan.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/apbps2.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/charrom_package.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/charrom.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/apbvga.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/svgactrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/grsysmon.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/gracectrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/grgpreg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/ahb_mst_iface.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/misc/grgprbank.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/net/net.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/pci.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/pcipads.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/pcitrace/pcitrace.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci1/pciahbmst.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/pcilib2.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/grpci2_ahb_mst.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/grpci2_phy.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/grpci2_phy_wrapper.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/grpci2.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/pci/grpci2/wrapper/grpci2_gen.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/uart.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/libdcom.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/apbuart.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/dcom.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/dcom_uart.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/uart/ahbuart.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/jtag.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/libjtagcom.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/jtagcom.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/bscanregs.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/bscanregsbd.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/jtagcom2.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/ahbjtag.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/jtag/ahbjtag_bsd.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/ethernet_mac.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greth.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greth_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greth_gbit.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greths.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greth_gbit_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/greths_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/grethm.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/grethm_mb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/rgmii.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/comma_detect.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/sgmii.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/elastic_buffer.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/gmii_to_mii.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/greth/adapters/word_aligner.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spacewire/spacewire.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/usb/grusb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddrpkg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddrintpkg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddrphy_wrap.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr2spax_ahb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr2spax_ddr.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr2buf.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr2spax.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr2spa.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr1spax.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddr1spax_ddr.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ddrspa.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2mig_7series_pkg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2mig_7series.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2mig_7series_ddr2_dq16_ad13_ba3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2mig_7series_ddr3_dq16_ad15_ba3.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2avl_async.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/ddr/ahb2avl_async_be.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/gr1553b/gr1553b_pkg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/gr1553b/gr1553b_pads.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/gr1553b/gr1553b_nlw.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/gr1553b/gr1553b_stdlogic.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2cmst.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2cmst_gen.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2cslv.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c2ahbx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c2ahb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c2ahb_apb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c2ahb_gen.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/i2c/i2c2ahb_apb_gen.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spi.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spimctrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spictrlx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spictrl.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spi2ahbx.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spi2ahb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/spi/spi2ahb_apb.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/grdmac_pkg.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/apbmem.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/grdmac_ahbmst.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/grdmac_alignram.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/grdmac.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/grdmac/grdmac_1p.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/subsys/subsys.vhd
read_vhdl -r -libname gaisler /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/gaisler/subsys/leon_dsu_stat_base.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/memoryctrl/memoryctrl.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/memoryctrl/mctrl.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/pci/pcicomp.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/pci/pci_arb_pkg.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/pci/pci_arb.vhd
read_vhdl -r -libname esa /mnt/D/CEFET/TCC/Leon3/grlib-gpl-1.5.0-b4164/lib/esa/pci/pciarb.vhd
